# Generated by Django 4.2.2 on 2023-06-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('file', models.URLField()),
                ('thumbnail', models.ImageField(blank=True, upload_to='')),
                ('view_count', models.PositiveIntegerField(default=0, editable=False)),
                ('like_count', models.PositiveIntegerField(default=0, editable=False)),
                ('dislike_count', models.PositiveIntegerField(default=0, editable=False)),
                ('comment_count', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
