# Generated by Django 4.2.2 on 2023-06-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='comments',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
